# Generated by Django 4.1.6 on 2023-02-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('RM', 'Remote')], max_length=20),
        ),
    ]
