# Generated by Django 4.1.6 on 2023-02-10 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_application_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='apply_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
