# Generated by Django 4.1.6 on 2023-02-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_job_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='user',
            new_name='owner',
        ),
    ]
