# Generated by Django 4.1.6 on 2023-02-13 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_job_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='owner',
        ),
    ]
